name: Publish

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          override: true
          target: wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: Npm clean install
        run: npm ci
      - name: Production build
        run: npm run prod:build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: rustboy
          directory: dist
          branch: main
